# Tap
tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'

# Div
brew 'coreutils'
brew 'bash-completion'
brew 'bash-git-prompt'
brew 'z'
brew 'speedtest-cli'
brew 'gh'
brew 'cask'
brew 'zsh'
brew 'zsh-syntax-highlighting'
brew 'maven'
brew 'maven-completion'
brew 'cheat'
brew 'vim'
brew 'nvim'
brew 'rustup-init'
brew 'golang'
brew 'wget'
brew 'helm'
brew 'python'
brew 'brew-pip'
brew 'node'
brew 'npm'
brew 'openshift-cli'
brew 'exa'
brew 'kubeseal'
brew 'thefuck'
brew 'fish'
brew 'starship'
brew 'kubernetes-cli'
brew 'kotlin'

# Casks
cask 'docker'
cask 'discord'
cask 'keystore-explorer'
cask 'font-jetbrains-mono'
cask 'font-jetbrains-mono-nerd-font'
cask 'visual-studio-code'
cask 'dotnet'



# Temurin Java
cask 'temurin'
cask 'temurin8'
cask 'temurin11'
cask 'temurin17'
